-- proctad_member_attendance_history
DROP VIEW IF EXISTS `proctad_member_attendance_history`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `proctad_member_attendance_history` AS select `pm`.`proctad_id` AS `proctad_id`,concat(`pm`.`first_name`,' ',ifnull(`pm`.`middle_name`,''),' ',`pm`.`last_name`,' ',ifnull(`pm`.`suffix`,'')) AS `member_name`,`pm`.`field_office_id` AS `field_office_id`,count(`ta`.`attendance_id`) AS `total_trainings`,sum(case when `ta`.`attendance_status` = 'present' then 1 else 0 end) AS `trainings_attended`,sum(case when `ta`.`qr_scan_timestamp` is not null then 1 else 0 end) AS `qr_scans_used`,max(`ta`.`created_at`) AS `last_training_date`,round(sum(case when `ta`.`attendance_status` = 'present' then 1 else 0 end) / count(`ta`.`attendance_id`) * 100,2) AS `attendance_rate` from (`proctad_members` `pm` left join `proctad_training_attendance` `ta` on(`pm`.`proctad_id` = `ta`.`proctad_id`)) group by `pm`.`proctad_id`,concat(`pm`.`first_name`,' ',ifnull(`pm`.`middle_name`,''),' ',`pm`.`last_name`,' ',ifnull(`pm`.`suffix`,'')),`pm`.`field_office_id`;


-- proctad_school_statistics
DROP VIEW IF EXISTS `proctad_school_statistics`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `proctad_school_statistics` AS select `es`.`exam_school_id` AS `school_id`,`es`.`exam_id` AS `exam_id`,`sc`.`school_name` AS `school_name`,count(distinct `r`.`exam_room_id`) AS `total_rooms`,sum(`r`.`capacity`) AS `total_capacity`,count(distinct `er`.`exam_room_id`) AS `configured_rooms`,count(distinct `sa`.`assignment_id`) AS `total_assigned`,sum(case when `sa`.`assignment_status` = 'confirmed' then 1 else 0 end) AS `confirmed_assignments`,sum(case when `sa`.`assignment_status` = 'pending' then 1 else 0 end) AS `pending_assignments`,round(count(distinct `sa`.`assignment_id`) / nullif(count(distinct `r`.`exam_room_id`),0) * 100,2) AS `assignment_progress`,case when count(distinct `sa`.`assignment_id`) >= count(distinct `r`.`exam_room_id`) then 'ready' when count(distinct `sa`.`assignment_id`) >= count(distinct `r`.`exam_room_id`) * 0.5 then 'partial' else 'insufficient' end AS `readiness_status` from ((((`proctad_exam_schools` `es` join `proctad_schools` `sc` on(`es`.`school_id` = `sc`.`school_id`)) left join `proctad_exam_rooms` `r` on(`es`.`exam_school_id` = `r`.`school_id`)) left join `proctad_exam_rooms` `er` on(`es`.`exam_school_id` = `er`.`school_id`)) left join `proctad_school_assignments` `sa` on(`es`.`exam_school_id` = `sa`.`school_id`)) group by `es`.`exam_school_id`,`es`.`exam_id`,`sc`.`school_name`;


-- proctad_training_attendance_stats
DROP VIEW IF EXISTS `proctad_training_attendance_stats`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `proctad_training_attendance_stats` AS select `tr`.`training_id` AS `training_id`,`tr`.`training_title` AS `training_title`,`tr`.`training_date` AS `training_date`,`tr`.`field_office_id` AS `field_office_id`,count(`ta`.`attendance_id`) AS `total_registered`,sum(case when `ta`.`attendance_status` = 'present' then 1 else 0 end) AS `total_present`,sum(case when `ta`.`attendance_status` = 'absent' then 1 else 0 end) AS `total_absent`,sum(case when `ta`.`qr_scan_timestamp` is not null then 1 else 0 end) AS `qr_scanned`,sum(case when `ta`.`scan_method` = 'manual' then 1 else 0 end) AS `manual_entry`,round(sum(case when `ta`.`attendance_status` = 'present' then 1 else 0 end) / count(`ta`.`attendance_id`) * 100,2) AS `attendance_rate` from (`proctad_training_records` `tr` left join `proctad_training_attendance` `ta` on(`tr`.`training_id` = `ta`.`training_id`)) group by `tr`.`training_id`,`tr`.`training_title`,`tr`.`training_date`,`tr`.`field_office_id`;


-- view_available_proctads_for_exam
DROP VIEW IF EXISTS `view_available_proctads_for_exam`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY INVOKER VIEW `view_available_proctads_for_exam` AS select distinct `tr`.`training_id` AS `briefing_id`,`tr`.`linked_exam_id` AS `exam_id`,`m`.`proctad_id` AS `proctad_id`,concat(`m`.`last_name`,', ',`m`.`first_name`,' ',ifnull(`m`.`middle_name`,'')) AS `full_name`,`m`.`agency` AS `agency`,`m`.`position` AS `position`,`m`.`contact_number` AS `contact_number`,`m`.`email` AS `email`,`m`.`field_office_id` AS `field_office_id`,`ta`.`time_in` AS `briefing_time_in`,`ta`.`qr_scan_timestamp` AS `briefing_qr_scan` from ((`proctad_training_records` `tr` join `proctad_training_attendance` `ta` on(`tr`.`training_id` = `ta`.`training_id` and `ta`.`attendance_status` = 'present')) join `proctad_members` `m` on(`ta`.`proctad_id` = `m`.`proctad_id`)) where `tr`.`training_type` = 'Briefing' and `tr`.`linked_exam_id` is not null and `m`.`accreditation_status` = 'active' and !exists(select 1 from `proctad_school_assignments` `sa` where `sa`.`proctad_id` = `m`.`proctad_id` and `sa`.`exam_id` = `tr`.`linked_exam_id` and `sa`.`assignment_status` in ('pending','confirmed') limit 1);
